In [8]:
import numpy as np
a=np.array([[10,20,30],[50,80,70]])
print(a)
print("Array created:",a)

[[10 20 30]
 [50 80 70]]
Array created: [[10 20 30]
 [50 80 70]]


In [10]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeroes:\n",c)


 Array with all zeroes:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
import numpy as np
d=np.random.random((3,3))
print("\nRandom values:\n",d)


Random values:
 [[0.5666796  0.36835666 0.10936131]
 [0.20344922 0.09231759 0.14982569]
 [0.11118997 0.27729024 0.85905803]]


In [13]:
import numpy as np
e=np.arange(0,40,5)
print("\n A sequence array with step5:\n",e)


 A sequence array with step5:
 [ 0  5 10 15 20 25 30 35]


In [15]:
import numpy as np
f=np.full((3,4),(7))
print(f)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [18]:
arr=np.array(([1,2,3,4],[10,20,30,40],[11,22,33,44]))
newarr=arr.reshape(4,3)
print("\n original array:\n",arr)
print("\n reshaped array:\n",newarr)


 original array:
 [[ 1  2  3  4]
 [10 20 30 40]
 [11 22 33 44]]

 reshaped array:
 [[ 1  2  3]
 [ 4 10 20]
 [30 40 11]
 [22 33 44]]


In [22]:
arr=np.array(([1,2,3,4],[10,20,30,40],[11,22,33,44]))
newtype=arr.astype('f')
print("\n converted array element:\n",newtype)
print("converted array tpe:",newtype)


 converted array element:
 [[ 1.  2.  3.  4.]
 [10. 20. 30. 40.]
 [11. 22. 33. 44.]]
converted array tpe: [[ 1.  2.  3.  4.]
 [10. 20. 30. 40.]
 [11. 22. 33. 44.]]
